import Head from 'next/head'
import Image from 'next/image'


import Top from '../components/About/top';
import Objective from '../components/About/Objective';
import AboutDirector from '../components/About/AboutDirector';


export default function Aboutmain() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen">
        <Top />
      </div>
      <div className="mt-20">
        <Objective />
      </div>
      <div className="pb-10 mt-5 md:mt-20">
      <AboutDirector />
      </div>
      
    </div >
  )
}
