import Head from 'next/head'
import Top from '../components/About/top';
import { useEffect, useState } from 'react';
import Objective from '../components/About/Objective';
import AboutDirector from '../components/About/AboutDirector';
import BarLoader from "react-spinners/BarLoader";
  

export default function Aboutmain({ data }) {
  const [loading, setloading] = useState(false);
  useEffect(() => {
    setloading(true);
    setTimeout(() => {
      setloading(false);
    }, 3000);
  }, [])
  return (
    <div>
       {loading == true && (
        <div className="flex flex-col justify-center items-center h-screen w-screen">
        <BarLoader
          color="#1329FE"
          height={4}
          width={100}
         
        />
       
      </div>
      )}
      {loading == false && (
        <div className="">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="h-screen">
          <Top />
        </div>
        <div className="mt-20">
          <Objective />
        </div>
        <div className="pb-10 mt-5 md:mt-20">
        <AboutDirector />
        </div>
        
      </div >
      )}
    
    </div>
  )
}
