import Head from 'next/head'
import Image from 'next/image'


import Reviews from '../components/Reviews'
import Courses from '../components/Courses'


export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen p-5">

      </div>



      <div className="px-8 py-4">

        <Courses />

      </div>


      <div className="p-4 ">
        <Reviews />
      </div>

    </div >
  )
}
